/**
 * 
 * ITEM 6: Explicitly disallow the use of compiler generated function you do not want.
 * 
 * THINGS TO REMEMBER
 * 
 * TO DISALLOW FUNCTIONALITY AUTOMATICALLY PROVIDED BY COMPILERS, DECLARE THE CORRESPONDING
 * MEMBER FUNCTIONS PRIVATE AND GIVE NO IMPLEMENTATIONS OR PARAMETER NAMES. uSING A BASE 
 * CLASS LIKE UNCOPYABLE IS ONE WAY TO DO THIS.
 * 
 * 
 */